### ISSUE TITLE
ofxPanelExtended::setSize bug

### ISSUE THREAD

**Issue by thomasgeissl** [frauzufall/ofxGuiExtended#13] opened 2015-07-17 10:36 UTC
I wonder how to size and position an ofxPanelExtended correctly. 
Width works as expected, height sets the y offset. 
For instance: `extendedPanel.setSize(width, 0);` will produce an overlap, so the panel header is not shown.
I will have a closer look into this next week.

``` c++
_oscInterfacePanel.setup("OSC Interface");
_oscInterfacePanel.setSize(ofGetWidth()/3, ofGetHeight()/8);
_oscInterfacePanel.setPosition(ofGetWidth()/3*2, ofGetHeight()/2);
_oscInterfacePanel.add(new ofxLabel(_model.getPWOSCInterface()->getRemoteHostSParameter()));
_oscInterfacePanel.add(new ofxIntSlider(_model.getPWOSCInterface()->getRemotePortIParameter()));
_oscInterfacePanel.add(new ofxIntSlider(_model.getPWOSCInterface()->getLocalPortIParameter()));
_oscInterfacePanel.add(new ofxToggle(_model.getPWOSCInterface()->getRelayBParameter()));
_oscInterfacePanel.add(new ofxToggle(_model.getPWOSCInterface()->getDebugBParameter()));
```

![screen shot 2015-07-17 at 11 53 55](https://cloud.githubusercontent.com/assets/3796674/8744948/79b5428c-2c7b-11e5-9554-34d9fd865520.png)

**Comment by frauzufall** [comment] 2015-07-17 11:57
The same thing happens if you use ofxPanel, right? This is the case because when you add an item the item is attached to the bottom of the panel and the panel height is extended by the item height.

It's working when you call the setSize() function after adding the controls. I can think about how to avoid this unexpected behavior.. But it has to be the same for ofxPanel then.

**Comment by thomasgeissl** [comment] 2015-07-17 12:51
Yes, it is an ofxPanel issue, I have not tested it with an ofxPanel before.

Not sure about the best way to solve this.
But it would be nice to set max height and calculate the actual height automatically every time an item is added. 

If I set the size after adding items then the width is not set correctly. 

``` c++
_oscInterfacePanel.setup("OSC Interface");
_oscInterfacePanel.setPosition(ofGetWidth()/3*2, ofGetHeight()/2);
_oscInterfacePanel.add(new ofxLabel(_model.getPWOSCInterface()->getRemoteHostSParameter()));
_oscInterfacePanel.add(new ofxIntSlider(_model.getPWOSCInterface()->getRemotePortIParameter()));
_oscInterfacePanel.add(new ofxIntSlider(_model.getPWOSCInterface()->getLocalPortIParameter()));
_oscInterfacePanel.add(new ofxToggle(_model.getPWOSCInterface()->getRelayBParameter()));
_oscInterfacePanel.add(new ofxToggle(_model.getPWOSCInterface()->getDebugBParameter()));
_oscInterfacePanel.setSize(ofGetWidth()/3, ofGetHeight()/8);
```

![screen shot 2015-07-17 at 14 30 01](https://cloud.githubusercontent.com/assets/3796674/8747135/783a81f0-2c90-11e5-808f-e4fb987daaa2.png)

**Comment by frauzufall** [comment] 2015-07-21 07:20
Alright, I looked into that. 
I corrected the first problem (it will take me a little bit to push it to github). You can set the size of the panel and the later added elements will have the desired width. But I won't set a fixed height. it will always adjust to the number of elements inside. I could also accept a fixed height, but its a little bit inconsistent since the panel is meant to shrink if you minimize a group inside. 
I would therefore recommend to use ofxGuiPage for your purpose. Its inherited from ofxPanelExtended, but it always keeps its size.

**Comment by thomasgeissl** [comment] 2015-07-21 08:01
Thanks a lot. 
I did not see a setter for the width, so I thought height is meant to be the max height. 
I will try ofxGuiPage.

**Comment by frauzufall** [comment] 2015-07-23 11:17
The changes are now in the master branch. It still looks different if you resize the panel before or after adding elements, this should be fixed with https://github.com/openframeworks/openFrameworks/pull/4123

**Closed as completed by frauzufall** 2015-07-23 11:17 UTC
Labels: bug
